Feat: Buttons for Dashboard
Smart-Grades/simple-grades pull request #42
Opened 2023-06-21 10:13 UTC by rezajaber

In this commit we introduce two new buttons for the dashboard which have the function to navigate the user easier through the different pages.

Daten ändern: Lets the user to change their data, meaning that if a student changes their university or major the dashboard will change its view too, to the subject of the new major and university.

Abmelden: Allows the user to sign out after being done!

2023-06-21 11:50 UTC, Lapotor requested changes
Please update branch to base.

2023-06-26 17:06 UTC, Lapotor approved these changes

2023-06-27 09:22 UTC, Lapotor approved these changes

2023-06-27 09:23 UTC, SahilFOM approved these changes

2023-06-27 09:23 UTC, SahilFOM approved these changes

2023-06-27 09:31 UTC, merged